---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: azure
lint:
  name: yamllint
platforms:
  - name: {{ cookiecutter.role_name}}-bionic
    resource_group_name: ${AZURE_RESOURCE_GROUP:-molecule}
    vm_size: Standard_B1s
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    become: true
scenario:
  name: {{ cookiecutter.scenario_name }}
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    sudo: true
