---
dependency:
  name: {{ cookiecutter.dependency_name }}
driver:
  name: {{ cookiecutter.driver_name }}
lint:
  name: {{ cookiecutter.lint_name }}
platforms:
{%- if cookiecutter.driver_name == 'azure' %}
  - name: {{ cookiecutter.role_name}}-bionic
    resource_group_name: ${AZURE_RESOURCE_GROUP:-molecule}
    vm_size: Standard_B1s
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest
{%- endif %}
provisioner:
  name: {{ cookiecutter.provisioner_name }}
  lint:
    name: {{ cookiecutter.provisioner_lint_name }}
  options:
    become: True
scenario:
  name: {{ cookiecutter.scenario_name }}
verifier:
  name: {{ cookiecutter.verifier_name }}
  lint:
    name: {{ cookiecutter.verifier_lint_name }}
  options:
    sudo: True

